[package]
name = "fadeluc-123/objectcache"
description = "A better way to cache 3D objects"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
    "src",
    "src/init.lua",
    "default.project.json",
    "wally.toml"
]

# [dependencies]
# TableUtil = "sleitnick/table-util@1.2.0"

[dev-dependencies]
objectcache = "fadeluc-123/objectcache@1.0.0"